update yazi config, remove tabs from all configs

diff --git a/scripts/.local/scripts/passmenu-ng b/scripts/.local/scripts/passmenu-ng
--- a/scripts/.local/scripts/passmenu-ng
+++ b/scripts/.local/scripts/passmenu-ng
@@ -6,8 +6,8 @@ menu_name="Get password"
 
 typeit=0
 if [[ $1 == "--type" ]]; then
-	typeit=1
-	shift
+    typeit=1
+    shift
 fi
 
 passcmd="pass"
@@ -24,14 +24,14 @@ fi
 echo "${extraction_cmd}"
 
 if [[ -n $WAYLAND_DISPLAY ]]; then
-	xdotool="wtype -"
+  xdotool="wtype -"
   dmenu="fuzzel -d"
 elif [[ -n $DISPLAY ]]; then
-	xdotool="xdotool type --clearmodifiers --file -"
+    xdotool="xdotool type --clearmodifiers --file -"
 else
   dmenu="rofi -dmenu"
-	echo "Error: No Wayland or X11 display detected" >&2
-	exit 1
+    echo "Error: No Wayland or X11 display detected" >&2
+    exit 1
 fi
 
 prefix=${PASSWORD_STORE_DIR-~/.password-store}
@@ -44,7 +44,7 @@ password=$(printf '%s\n' "${password_files[@]}" | $dmenu -p "${menu_name}: ")
 [[ -n $password ]] || exit
 
 if [[ $typeit -eq 0 ]]; then
-	$passcmd show -c "$password" 2>/dev/null
+    $passcmd show -c "$password" 2>/dev/null
 else
-	$passcmd show "$password" | $extraction_cmd | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
+    $passcmd show "$password" | $extraction_cmd | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
 fi
