refactor scripts, add fuzzel

diff --git a/scripts/scripts/powermenu b/scripts/scripts/powermenu
--- a/scripts/scripts/powermenu
+++ b/scripts/scripts/powermenu
@@ -1,3 +1,13 @@
 #!/bin/sh
-selection=$(printf "%s\n" poweroff reboot hibernate suspend | rofi -dmenu -p "Shutdown menu")
+
+if [ -n "$WAYLAND_DISPLAY" ]; then
+  dmenu="fuzzel -d"
+elif [ -n "$DISPLAY" ]; then
+  dmenu="rofi -dmenu"
+else
+  echo "Error: No Wayland or X11 display detected" 1>&2
+  exit 1
+fi
+selection=$(printf "%s\n" poweroff reboot hibernate suspend | $dmenu -p "Shutdown menu")
 [ -n "$selection" ] && sync && loginctl "$selection"
+
diff --git a/scripts/scripts/translate b/scripts/scripts/translate
--- a/scripts/scripts/translate
+++ b/scripts/scripts/translate
@@ -7,10 +7,10 @@ elif [ -n "$DISPLAY" ]; then
   text="$(xsel -o)"
   copycmd="xsel -ib"
 else
-  echo "Error: No Wayland or X11 display detected"
+  echo "Error: No Wayland or X11 display detected" 1>&2
 fi
 translated="$(trans -b :ru "$text")"
 zenity --info --title "Translation" --text "$translated" &
-printf "$translated" | $copycmd
+printf "%s" "$translated" | $copycmd
 notify-send "Translation was copied to the clipboard"
 
